name: first workflow
on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: "this is version name for github workflow"
   # repository_dispatch:
    #  types: [test]  
    #push:
     # branches:
      #  - "main"
   # pull_request:
    #  branches:
     #   - "main"
     # types: [opened, closed]    
jobs:
    first-workflow-job:
        name: "first job"
        runs-on: ubuntu-latest
        steps:
          - name: before checkout action
            run: ls
            shell: bash

          - name: checkout steps
            uses: actions/checkout@v4

          - name: after checkout action 
            run: ls
            shell: bash
